### Test du controller Projects
@baseUrl = http://localhost:3002/api
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzgwMzE4MjM0LCJleHAiOjE3ODA0MDQ2MzR9.Zbbkl92_KZkReDdvSvC8bQgoIOjX98e2yBWcaYkFZrQ



### Login - admin seedé
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "thomas.martin@email.fr",
  "password": "Password123@"
}

###
GET {{baseUrl}}/carts
Authorization: Bearer {{userToken}}

