### Test du controller Projects

GET http://localhost:3002/projects?page=1
Accept: application/json

### Obtenir un projet par slug
GET http://localhost:3002/projects/reforestation-bretagne
Accept: application/json

### Obtenir les arbres d'un projet par slug
GET http://localhost:3002/projects/reforestation-bretagne/trees?page=1
Accept: application/json
